// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvegnmstmgpgzlzowblb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12ZWdubXN0bWdwZ3psem93YmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTI0OTAsImV4cCI6MjA2NzI2ODQ5MH0.8b9qCehXIAUUQSFBcIYZnXLkfmvaMlchN64TWULEB1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});